# Generated by Django 4.1.5 on 2023-02-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kidchoice',
            options={'verbose_name': 'Допалнительный кружок', 'verbose_name_plural': 'Допалнительные кружки'},
        ),
        migrations.AlterField(
            model_name='kindergarden',
            name='area',
            field=models.CharField(choices=[('Lasnamae', 'Lasnamae'), ('Kristiine', 'Kristiine'), ('Noome', 'Noome')], max_length=30),
        ),
    ]
