# Generated by Django 4.1.5 on 2023-01-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergarden',
            name='addition',
            field=models.CharField(choices=[('Sw', 'Swiming'), ('jum', 'jumping'), ('R', 'Run'), ('S', 'Site')], default='R', max_length=3),
        ),
    ]
