# Generated by Django 4.1.5 on 2023-01-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_kindergarden_addition'),
    ]

    operations = [
        migrations.CreateModel(
            name='KIDCHOICE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=154, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='kindergarden',
            name='free_places',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='kindergarden',
            name='addition',
        ),
        migrations.AddField(
            model_name='kindergarden',
            name='addition',
            field=models.ManyToManyField(to='account.kidchoice'),
        ),
    ]
